// A static server over `gui/src`, shared by every tool that has to drive the app in a browser.
//
// Extracted from assert.mjs when S8 needed a second one. The tray glyphs the desktop loads are
// generated by rendering the very sheet the fidelity gate asserts — `?frame=10a Glyph states` — so
// that the icon on a panel and the mark in the gate are the same node rather than two drawings that
// agree today. That means two tools now need a server, and two copies of a path-normalising static
// handler is exactly the shape of duplication this codebase keeps finding bugs in.
//
// Served rather than opened as `file://` because the app is ES modules and a module graph over
// `file://` hits cross-origin rules the real webview never does. Tauri serves `gui/src` the same way.

import { createServer } from "node:http";
import { readFileSync, statSync } from "node:fs";
import { dirname, extname, join, normalize, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
export const SRC = resolve(HERE, "..", "..", "src");

const MIME = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".mjs": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".woff2": "font/woff2",
  ".png": "image/png",
};

/** Listen on an ephemeral port. Resolves to `{ server, port }`; the caller closes the server. */
export function serve() {
  return new Promise((ready) => {
    const server = createServer((req, res) => {
      const rel = normalize(decodeURIComponent(new URL(req.url, "http://x").pathname)).replace(
        /^(\.\.[/\\])+/,
        "",
      );
      let file = join(SRC, rel);
      try {
        if (statSync(file).isDirectory()) file = join(file, "index.html");
      } catch {
        res.writeHead(404).end("not found");
        return;
      }
      try {
        const body = readFileSync(file);
        res.writeHead(200, { "content-type": MIME[extname(file)] ?? "application/octet-stream" }).end(body);
      } catch {
        res.writeHead(404).end("not found");
      }
    });
    server.listen(0, "127.0.0.1", () => ready({ server, port: server.address().port }));
  });
}
